#!/bin/bash

user_exists=$(getent passwd $1)
if [[ $EUID -ne 0 ]]; # check if script is being run as root
then
	echo "This script must be run as root"
	exit 1
elif [ -z $user_exists ] #True if the string is null(empty)
then
	echo "User doesn't exist"
	exit 1
else
	userdel "$1"
fi
